"use client";

import { useCallback, useEffect, useMemo, useState } from "react";

import { CodeEditor } from "@/features/code/CodeEditor";
import {
  generateCodeChallenge,
  type AdaptiveContract,
  type ChallengeRead,
  type DifficultyLevel,
} from "@/lib/api";

const DEFAULT_ASSESSMENT_ID = "coding-tool-demo";

function newSessionId(): string {
  if (typeof crypto !== "undefined" && "randomUUID" in crypto) {
    return crypto.randomUUID();
  }
  return `session-${Date.now()}`;
}

export interface CodeChallengeViewProps {
  initialChallengeId?: number;
}

export function CodeChallengeView({ initialChallengeId }: CodeChallengeViewProps) {
  const [sessionId] = useState(newSessionId);
  const [challenge, setChallenge] = useState<ChallengeRead | null>(null);
  const [questionIndex, setQuestionIndex] = useState(0);
  const [difficulty, setDifficulty] = useState<DifficultyLevel>("beginner");
  const [activeContract, setActiveContract] = useState<AdaptiveContract | null>(null);
  const [loading, setLoading] = useState(true);
  const [generatingNext, setGeneratingNext] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const loadGeneratedChallenge = useCallback(
    async (contract?: AdaptiveContract | null) => {
      setError(null);
      try {
        const result = await generateCodeChallenge({
          session_id: sessionId,
          assessment_id: DEFAULT_ASSESSMENT_ID,
          contract: contract ?? undefined,
        });
        setChallenge(result.challenge);
        setActiveContract(result.contract);
        setQuestionIndex(result.contract.question_index);
        setDifficulty(result.contract.difficulty);
      } catch (err) {
        setError(
          err instanceof Error ? err.message : "Failed to generate challenge",
        );
        if (!contract) setChallenge(null);
        throw err;
      }
    },
    [sessionId],
  );

  useEffect(() => {
    if (initialChallengeId != null) {
      setLoading(false);
      return;
    }
    (async () => {
      try {
        await loadGeneratedChallenge();
      } finally {
        setLoading(false);
      }
    })();
  }, [initialChallengeId, loadGeneratedChallenge]);

  const handleSubmitted = useCallback(
    async ({ contract }: { contract: AdaptiveContract }) => {
      setActiveContract(contract);
      if (contract.stop) {
        setChallenge(null);
        return;
      }
      setGeneratingNext(true);
      setError(null);
      try {
        await loadGeneratedChallenge(contract);
      } catch {
        // Error state is set in loadGeneratedChallenge.
      } finally {
        setGeneratingNext(false);
      }
    },
    [loadGeneratedChallenge],
  );

  const sessionLabel = useMemo(() => sessionId.slice(0, 8), [sessionId]);

  if (loading) {
    return (
      <p className="text-sm text-neutral/70">LLM is authoring your first challenge…</p>
    );
  }

  return (
    <div className="mx-auto flex w-full max-w-4xl flex-col gap-6">
      <header className="space-y-1">
        <h1 className="text-2xl font-semibold text-neutral">Adaptive coding</h1>
        <p className="text-sm text-neutral/70">
          Each question is generated by the LLM from your session contract. Submit
          runs E2B sandbox grading, LLM rubric judging, memory extraction, and
          adaptation — then authors the next challenge.
        </p>
        <p className="text-xs text-neutral/50">
          Session {sessionLabel}… · assessment {DEFAULT_ASSESSMENT_ID}
        </p>
      </header>

      {activeContract && !activeContract.stop && (
        <div className="rounded-lg border border-border bg-surface-muted p-3 text-sm text-neutral/80">
          Question {questionIndex + 1} ·{" "}
          <span className="font-medium capitalize">{difficulty}</span>
          {activeContract.focus_dimension && (
            <>
              {" "}
              · focus{" "}
              <span className="font-medium">
                {activeContract.focus_dimension.replace("_", " ")}
              </span>
            </>
          )}
          {activeContract.memory_summary && (
            <p className="mt-1 text-xs text-neutral/60">
              {activeContract.memory_summary}
            </p>
          )}
        </div>
      )}

      {generatingNext && (
        <p className="rounded-lg border border-primary/20 bg-primary/5 p-3 text-sm text-primary">
          Submit complete — LLM is authoring your next challenge…
        </p>
      )}

      {error && (
        <div className="space-y-2">
          <p className="rounded-lg border border-error/30 bg-error/5 p-3 text-sm text-error">
            {error}
          </p>
          <button
            type="button"
            onClick={() => void loadGeneratedChallenge(activeContract)}
            className="rounded-lg border border-border bg-white px-3 py-2 text-sm font-medium text-neutral hover:bg-surface-muted"
          >
            Retry generation
          </button>
        </div>
      )}

      {challenge && (
        <CodeEditor
          key={`${challenge.id}-${questionIndex}-${difficulty}`}
          challenge={challenge}
          sessionId={sessionId}
          assessmentId={DEFAULT_ASSESSMENT_ID}
          questionIndex={questionIndex}
          difficulty={difficulty}
          onSubmitted={handleSubmitted}
          disabled={generatingNext}
        />
      )}

      {activeContract?.stop && (
        <p className="rounded-lg border border-border bg-surface-muted p-4 text-sm text-neutral">
          Adaptive loop complete after {activeContract.question_index} question(s).{" "}
          {activeContract.memory_summary}
        </p>
      )}
    </div>
  );
}
